services:
  client:
    depends_on:
    - server
    build:
      context: .
      dockerfile: ./cmd/grpcclient/Dockerfile
      target: dev
    volumes:
      - ./cmd/grpcclient/:/go/src/app/cmd/app
    tty: true
    environment:
      - SERVER_ENDPOINT=server:50051

  server:
    build:
      context: .
      dockerfile: ./cmd/grpcserver/Dockerfile
      target: dev
    volumes:
      - ./cmd/grpcserver/:/go/src/app/cmd/app
    tty: true
