name: Go-Build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  grpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: GoReleaser (grpc)
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --snapshot --clean
          workdir: grpc
      - name: Docker build
        run: |
          set -euo pipefail
          export PATH="$(go env GOPATH)/bin:$PATH"
          set -x
          docker build -t grpcclient -f cmd/grpcclient/Dockerfile --target prod .
          docker build -t grpcserver -f cmd/grpcserver/Dockerfile --target prod .
        working-directory: grpc
